elevar_crm/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # root router
    path('', include('main_app.urls')),
    # auth router
    path('accounts/', include('django.contrib.auth.urls')),
]

main_app/urls.py
from django.urls import path
from . import views
from .views import line_chart, line_chart_json

urlpatterns = [
    # graphs
    path('chart', line_chart, name='line_chart'),
    path('chartJSON', line_chart_json, name='line_chart_json'),

    # home route
    path('', views.home, name='home'),
    # signup route
    path('account/signup/', views.signup, name='signup'),
    # about route
    path('about/', views.about, name='about'),
    # dashboard route
    path('dashboard/', views.dashboard, name="dashboard"),

    ###############
    ## account
    ###############
    # # index route for account
    path('account/', views.account_index, name="account_index"),
    # # detail route for account
    path('account/<int:account_id>/', views.account_detail, name="account_detail"),
    # create route for account
    path('account/create/', views.account_create, name="account_create"),
    # update route for account
    path('account/<int:pk>/update', views.AccountUpdate.as_view(), name="account_update"),
    # delete route for card
    path('account/<int:pk>/delete/', views.AccountDelete.as_view(), name="account_delete"),


    # ###############
    # ## Contacts
    # ###############
    # # index route for contacts
    path('contact/', views.ContactList.as_view(), name="contact_index"),
    # # detail route for contacts
    path('contact/<int:pk>/', views.ContactDetail.as_view(), name="contact_detail"),
    # create route for contacts
    path('account/<int:account_id>/contact_create/', views.contact_create, name="contact_create"),
    # update route for contacts
    path('contact/<int:pk>/update', views.ContactUpdate.as_view(), name="contact_update"),
    # delete route for card
    path('contact/<int:pk>/delete/', views.ContactDelete.as_view(), name="contact_delete"),

    # ###############
    # ## Products
    # ###############
    # # index route for products
    path('product/', views.ProductList.as_view(), name="product"),
    # detail route for products
    path('product/<int:pk>/', views.ProductDetail.as_view(), name="product_detail"),
    # create route for products
    path('product/create/', views.ProductCreate.as_view(), name="product_create"),
    # update route for products
    path('product/<int:pk>/update/', views.ProductUpdate.as_view(), name="product_update"),
    # delete route for card
    path('product/<int:pk>/delete/', views.ProductDelete.as_view(), name="product_delete"),
    # add a photo to a product
    path('product/<int:product_id>/add_photo/', views.add_photo, name="add_photo"),

    #################
    ## Transactions
    #################
    # Update / Change Status transaction
    path('transaction/<int:pk>/update/', views.TransactionUpdate.as_view(), name="transaction_update"),
    #################
    ## Relationships
    #################
    # # 1:M account to transactions
    path('account/<int:account_id>/add_transaction/', views.add_transaction, name="add_transaction"),
    # # M:M associating a account to products
    path('account/<int:account_id>/assoc_product/<int:product_id>/', views.assoc_product, name="assoc_product"),
    # # route for removing a product from a account
    path('account/<int:account_id>/remove_product/<int:product_id>/', views.remove_product, name="remove_product"),
]

main_app/models.py
from django.db import models
from django.forms import IntegerField
from django.urls import reverse
from datetime import date
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
import uuid


# Create your models here.
class Product(models.Model):
	name = models.CharField(max_length=100)
	price = models.IntegerField()
	description = models.TextField(max_length=300)

	def __str__(self):
		return f'Product {self.name} with a price of {self.price}'
	
	def get_absolute_url(self):
		return reverse('product_detail', kwargs = {'pk': self.id})

class Account(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	products = models.ManyToManyField(Product)
	company_name = models.CharField(max_length=100)
	industry = models.CharField(max_length=100)
	state = models.CharField(max_length=100)
	city = models.CharField(max_length=100)
	country = models.CharField(max_length=100)
	zip = models.IntegerField()
	description = models.TextField(max_length=250)

	def __str__(self):
		return f"{self.company_name}"

	def get_absolute_url(self):
		return reverse('account_detail', kwargs={'account_id': self.id}) 


class Contact(models.Model):
	first_name = models.CharField(max_length=100)
	last_name = models.CharField(max_length=100)
	title = models.CharField(max_length=100)
	phone = PhoneNumberField(unique = True, null = False, blank = False)
	email = models.CharField(max_length=100)
	account = models.ForeignKey(Account, on_delete=models.CASCADE)

	def __str__(self):
		return f" This is {self.first_name}, {self.last_name}"

	def get_absolute_url(self):
		return reverse("contact_detail", kwargs={"pk": self.id})


class Photo(models.Model):
	url = models.CharField(max_length=200)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	def __str__(self):
		return f'Photo for product_id: {self.product_id} @{self.url}'

# Transaction Model
STATUS = (
	('P', 'In Progress'),
	('I', 'Incomplete'),
	('C', 'Completed'),
)
class Transaction(models.Model):
	serial_number =  models.CharField(max_length=100, default=000000) 
	date = models.DateField('transaction date')
	status = models.CharField(
		max_length=1,
		choices=STATUS,
		default=STATUS[0][0]
	)
	price = models.IntegerField()
	account = models.ForeignKey(Account, on_delete=models.CASCADE)
	def __str__(self):
		return f'Transaction #{self.serial_number}: {self.account.company_name} {self.price} {self.date}'

	def get_absolute_url(self):
		return reverse("account_detail", kwargs={"account_id": self.objects.account_id})
	
	class Meta:
		ordering = ['-date']

main_app/forms.py
from dataclasses import fields
from django.forms import ModelForm
from .models import Contact, Account, Transaction

class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ['first_name', 'last_name', 'title', 'phone', 'email']

class AccountForm(ModelForm):
    class Meta:
        model = Account
        fields = ['company_name', 'industry', 'state', 'city', 'country', 'zip', 'description']

class TransactionForm(ModelForm):
    class Meta:
        model = Transaction
        fields = ['date', 'price']

main_app/views.py
from ast import Del
from dataclasses import fields
from django.urls import reverse
from django.shortcuts import render, redirect
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
import uuid
import boto3
from .models import Account, Contact, Photo, Product, Transaction
from .forms import ContactForm, AccountForm, TransactionForm
from django.views.generic import TemplateView
from chartjs.views.lines import BaseLineChartView
from chartjs.views.columns import BaseColumnsHighChartsView
import environ


class LineChartJSONView(BaseLineChartView):
    def get_labels(self):
        """Return 7 labels for the x-axis."""
        return ["January", "February", "March", "April", "May", "June", "July"]

    def get_providers(self):
        """Return names of datasets."""
        return ["Apple", "Google", "Microsoft"]

    def get_data(self):
        """Return 3 datasets to plot."""
        return [[45, 48, 57, 55, 54, 59, 56],
                [41, 44, 42, 47, 50, 48, 53],
                [37, 41, 42, 46, 48, 54, 60]]


class ColumnHighChartJSONView(BaseColumnsHighChartsView):
    title = "Column Highchart test"
    yUnit = "%"
    providers = ["All"]
    credits = {"enabled": False}


env = environ.Env()
environ.Env.read_env()
line_chart = TemplateView.as_view(template_name='line_chart.html')
line_chart_json = LineChartJSONView.as_view()

env = environ.Env()
environ.Env.read_env()

S3_BASE_URL = 'https://s3.us-west-2.amazonaws.com/'
BUCKET = env('S3_PICTURES_BUCKET')

# Create your views here.


def home(request):
    if request.user.is_authenticated:
        return redirect('dashboard')

    return render(request, 'home.html')


@login_required
def dashboard(request):
    # todo transactions go here
    accounts = Account.objects.filter(user=request.user)
    # account = Account.objects.get(id=account_id, user=request.user)
    # if not account.user == request.user:
    #     return redirect('home')
    products = Product.objects.all()
    employees = Contact.objects.all()
    transactions = Transaction.objects.all()


    return render(request, 'dashboard.html', {
        'accounts': accounts,
        # 'account': account,
        'products': products,
        'employees': employees,
        'transactions': transactions,
    })



def about(request):
    return render(request, 'about.html')


def signup(request):
    error_message = ''
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('home')
        else:
            error_message = "Invaild sign up - try again"
    form = UserCreationForm()
    context = {'form': form, "error_message": error_message}
    return render(request, 'registration/signup.html', context)

################
## Account Views
################


@login_required
def account_index(request):
    accounts = Account.objects.filter(user=request.user)
    account_form = AccountForm()
    return render(request, 'account/index.html', {
        'accounts': accounts,
        'account_form': account_form,
    })


@login_required
def account_detail(request, account_id):
    account = Account.objects.get(id=account_id, user=request.user)
    #todo! rendering product in details page
    if not account.user == request.user:
        return redirect('home')
    transaction_form = TransactionForm()
    contact_form = ContactForm()
    products = Product.objects.all()
    employees = Contact.objects.filter(account_id=account_id)
    product_not_in_acc = Product.objects.exclude(id__in = account.products.all().values_list('id'))

    return render(request, 'account/detail.html', {
        'account': account,
        'employees': employees,
        'contact_form': contact_form,
        'transaction_form': transaction_form,
        'products': products,
        'prod' : product_not_in_acc,
    })


@login_required
def account_create(request):
    form = AccountForm(request.POST)
    if form.is_valid():
        new_contact = form.save(commit=False)
        new_contact.user = request.user
        new_contact.save()
    return redirect('account_index')


class AccountUpdate(LoginRequiredMixin, UpdateView):
    model = Account
    fields = ['company_name', 'industry', 'state',
              'city', 'country', 'zip', 'description']

    def get_object(self, queryset=None):
        account = super(AccountUpdate, self).get_object()
        if not account.user == self.request.user:
            return redirect('home')
        return account


class AccountDelete(LoginRequiredMixin, DeleteView):
    model = Account
    success_url = '/account/'

    def get_object(self, queryset=None):
        account = super(AccountDelete, self).get_object()
        if not account.user == self.request.user:
            return redirect('home')
        return account
################
## Contact Views
################


class ContactList(LoginRequiredMixin, ListView):
    model = Contact

    def get_object(self, queryset=None):
        contact = super(ContactList, self).get_object()
        if not contact.account == self.request.account:
            return redirect('home')
        return contact


class ContactDetail(LoginRequiredMixin, DetailView):
    model = Contact

    #todo! authorization logic needed
    # def get_object(self, queryset=None):
    #     contact = super(ContactDetail, self).get_object()
    #     if not contact.account == self.request.account:
    #         return redirect('home')
    #     return contact


def contact_create(request, account_id):
    account = Account.objects.get(id=account_id, user=request.user)
    if not account.user == request.user:
        return redirect('home')
    form = ContactForm(request.POST)
    if form.is_valid():
        new_contact = form.save(commit=False)
        new_contact.account_id = account_id
        new_contact.save()
    return redirect('account_detail', account_id=account_id)


class ContactUpdate(LoginRequiredMixin, UpdateView):
    model = Contact
    fields = ['first_name', 'last_name', 'title', 'phone', 'email']


class ContactDelete(LoginRequiredMixin, DeleteView):
    model = Contact
    success_url = '/contact/'


#################
## Product Views
#################
class ProductList(LoginRequiredMixin, ListView):
    model = Product

    def get_object(self, queryset=None):
        product = super(ProductList, self).get_object()
        if not product.account == self.request.account:
            return redirect('home')
        return product


class ProductDetail(LoginRequiredMixin, DetailView):
    model = Product


class ProductCreate(LoginRequiredMixin, CreateView):
    model = Product
    fields = ['name', 'price', 'description']


class ProductUpdate(LoginRequiredMixin, UpdateView):
    model = Product
    fields = ['name', 'price', 'description']


class ProductDelete(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = '/product/'


@login_required
def add_photo(request, product_id):
    # todo product authorization
    # product = Product.objects.get(id=product_id, user=request.user)
    # if not product.user == request.user:
    #     return redirect('home')
    # return product
    # photo-file will be the 'name' attribute on the <input type="file">
    photo_file = request.FILES.get('photo-file', None)
    print(f"this is photo_file -->> {photo_file}")
    if photo_file:
        s3 = boto3.client('s3')
        # need a unique 'key' for s3 / needs file extension
        key = uuid.uuid4().hex[:6] + \
            photo_file.name[photo_file.name.rfind('.')]
        print(f"this is key -->> {key}")
        # error handling
        try:
            s3.upload_fileobj(photo_file, BUCKET, key)
            url = f"{S3_BASE_URL}{BUCKET}/{key}"
            photo = Photo(url=url, product_id=product_id)
            print(f"this is photo in try block -->> {photo}")
            photo.save()
        except:
            print('An error occured')
    return redirect("product_detail", pk=product_id)


@login_required
def assoc_product(request, account_id, product_id):
    Account.objects.get(
        id=account_id, user=request.user).products.add(product_id)
    return redirect('account_detail', account_id=account_id)


@login_required
def remove_product(request, account_id, product_id):
    Account.objects.get(
        id=account_id, user=request.user).products.remove(product_id)
    return redirect('account_detail', account_id=account_id)

#########################
## Transaction
#########################


@login_required
def add_transaction(request, account_id):
    account = Account.objects.get(id=account_id, user=request.user)
    if not account.user == request.user:
        return redirect('home')
    form = TransactionForm(request.POST)
    if form.is_valid():
        new_transaction = form.save(commit=False)
        new_transaction.account_id = account_id
        new_transaction.serial_number = uuid.uuid4().hex[:10]
        new_transaction.save()
    return redirect('account_detail', account_id=account_id)


class TransactionUpdate(LoginRequiredMixin, UpdateView):
    model = Transaction
    fields = ['status']
    
    def get_success_url(self):
        return reverse("account_detail", kwargs={"account_id": self.object.account_id}) 

main_app/templates/main_app/account_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Account</h1>

  <h4>Are you sure you want to delete <br> <hr> <span class="teal-text">{{ object.company_name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <button type="submit" class="btn"><i class="material-icons right">delete</i>Delete</button>
    <a href="{% url 'account_detail' object.id %}" class="btn">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/account_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Contact</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/contact_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Contact</h1>

  <h4>Are you sure you want to delete <br> <hr> <span class="teal-text">{{ object.first_name }} {{ object.last_name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'contact_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/contact_detail.html
{% extends 'base.html' %} {% block content %}
<div class="flex flex-col">
  <h1 class="contact-details-title">
    <span>Contact Details</span>
    <div class="contact-details-icons-wrapper">
      <a href="tel:{{contact.phone}}"><i class="fa-solid fa-phone small"></i></a>
      <a href="mailto:{{contact.email}}"><i class="fa-solid fa-envelope small"></i></a>
      <i class="fa-solid fa-comment-dots small"></i>
    </div>
  </h1>

  <div id="contact-details" class="contact-details">
    <div class="col s5 offset-s1">
      <div class="card #00796b teal darken-2 contact-details-wrapper hoverable z-depth-4">
        <div class="card-content white-text">
          <span class="card-title">
            {{ contact.first_name }} {{contact.last_name}}
          </span>
          <ul class="contact-display">
            <li class="contact-item">Phone: <span class="right">{{contact.phone}}</span></li>
            <li class="contact-item">Title: <span class="right">{{contact.title}}</span></li>
            <li class="contact-item">Email: <span class="right">{{contact.email}}</span></li>
            <li class="contact-item">
              Company: <span class="right">{{contact.account.company_name}}</span>
            </li>
          </ul>
        </div>
        <div class="card-action">
          <a href="{% url 'contact_update' contact.id %}">Edit</a>
          <a href="{% url 'contact_delete' contact.id %}" class="right">Delete</a>
        </div>
      </div>
    </div>

    <div class="col s5">
      <div id="contact-account-card" class="card #00796b teal darken-2 contact-details-wrapper hoverable z-depth-4">
        <div class="card-content white-text">
          <span class="card-title"> {{contact.account.company_name}} </span>
          <ul class="contact-company-info ">
            <li class="company-contact">Industry: <span class="right">{{contact.account.industry}}</span></li>
            <hr>
            <li class="location">Location:
              <span class="right">
                {{contact.account.city}}, {{contact.account.state}},
                {{contact.account.country}}
              </span>
            </li>
            <li class="company-contact right">Description: <br><blockquote class="flow-text">{{contact.account.description}}</blockquote></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

main_app/templates/main_app/contact_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Contact</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/contact_list.html
{% extends 'base.html' %} {% block content%}

<h1>Contacts List</h1>
{% for contact in contact_list %}
<a href="{% url 'contact_detail' contact.id %}">
  <div class="card">
    <div class="card-content">
      <span class="card-title"> {{ contact.first_name }} </span>
    </div>
  </div>
</a>
{% endfor %} {% endblock %}

main_app/templates/main_app/product_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

  <h1>Delete Product</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'product_detail' object.id %}">Cancel</a>
  </form>

{% endblock %}

main_app/templates/main_app/product_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Product Details</h1>

<div class="row s12">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ product.name }}</span>
        <br>
        <hr>
        <h4>Price:</h4>
        <h5 class="right-align"><span>${{ product.price }}</span></h5>
        <br>
        <hr>
        <p>{{ product.description }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'product_update' product.id %}">Edit</a>
        <a href="{% url 'product_delete' product.id %}">Delete</a>
      </div> 
    </div>
  </div>
  <div class="col s6">
    <div class="card">
      <div class="card-content">
        {% for photo in product.photo_set.all %}
          <img class="responsive-img" src="{{photo.url}}" alt="Product Image"/>
        {% empty %}
          <div class="card-panel teal-text center-align">No Photos Uploaded</div>
        {% endfor %}
          <form action="{% url 'add_photo' product.id %}" enctype="multipart/form-data" method="POST" class="card-panel">
            {% csrf_token %}
            <input type="file" name="photo-file"/>
            <br><br>
            <input type="submit" class="btn" vaule="Upload Photo"/>
          </form>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/product_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add A New Product</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/product_list.html
{% extends 'base.html' %}
{% block content %}

<div class="product-header valign-wrapper">
  <h1>Products</h1>
  <a class=" btn waves-effect waves-light hoverable " href="{% url 'product_create' %}"><i class="fa-solid fa-circle-plus"></i><span>Create Product</span></a>
</div>
<div class="products row">

{% for product in product_list %}
  <a href="{% url 'product_detail' product.id %}" class="col s4">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ product.name }} </span>
        </div>
    </div>
  </a>
{% endfor %}
</div>

{% endblock %}

main_app/templates/main_app/transaction_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/transactions_form.html
{% extends 'base.html' %}

{% block content %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}